---
- hosts: kube-master
  tasks:
# Step 1: Configuring mgmt server for connecting to k8s cluster
    - name: Copy kube config from k8s cluster
      fetch:
        src: /root/.kube/config
        #dest: /var/lib/jenkins/config
        dest: /root/.kube/config
        flat: yes

    #- fetch:
    #    src: /root/.kube/config
    #    dest: /root/.kube/config
    #    flat: yes

# Step 2: Adding --cloud-provider=aws in kube services manifests
    - name: Inserting a line (--cloud-provider) to kube-controller-manager.yaml
      lineinfile:
        path: /etc/kubernetes/manifests/kube-controller-manager.yaml
        line: '    - --cloud-provider=aws'
        insertafter: '- --node-cidr-mask-size=24'

# Step 3: Adding --cloud-provider=aws in kube services manifests
    - name: Inserting a line (--cloud-provider) to kube-apiserver.yaml
      lineinfile:
        path: /etc/kubernetes/manifests/kube-apiserver.yaml
        line: '    - --cloud-provider=aws'
        insertafter: '- --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key'

# Step 4: Adding an exrea flag --cloud-provider=aws to 10-kubeadm.conf
    - name: Inserting a line (--cloud-provider) to 10-kubeadm.conf
      lineinfile:
        path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
        line: 'Environment="KUBELET_EXTRA_ARGS=--cloud-provider=aws'
        insertafter: 'Environment="KUBELET_CERTIFICATE_ARGS=--rotate-certificates=true --cert-dir=/var/lib/kubelet/pki'

# Step 5: Restarting services
    - name: reload systemd
      sudo: yes
      command: systemctl daemon-reload

    - name: kubelet restart
      sudo: yes
      command: systemctl system restart

   - name:  kubelet restart 2
     service:
       name: kubelet
       daemon_reload: yes
       state: restarted
