# Step 2.1: Install Docker and its dependent components.

- name: Install packages that allow apt to be used over HTTPS
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add an apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt repository for stable version
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: Install docker and its dependecies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  notify:
    - docker status

- name: Add vagrant user to docker group
  user:
    name: vagrant
    group: docker

# Step 2.2: Kubelet will not start if the system has swap enabled, so we are disabling swap using the below code.


- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0





# Step 2.3: Installing kubelet, kubeadm and kubectl using the below code.





- name: disable SELinux
  command: setenforce 0

- name: disable SELinux on reboot
  selinux:
   state: disabled


- name: add Kubernetes' YUM repository
  yum_repository:
    name: Kubernetes
    description: Kubernetes YUM repository
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: yes

- name: install kubelet
  yum:
    name: kubelet-1.10.12
    state: present
    update_cache: true

- name: install kubeadm
  yum:
    name: kubeadm-1.10.12
    state: present
- name: install kubectl
  yum:
    name: kubectl-1.10.12
    state: present
    allow_downgrade: yes


- name: start kubelet
  service:
    name: kubelet
    enabled: yes
    state: started





# Step 3.2: Join the nodes to the Kubernetes cluster using below code.
- name: Copy the join command to server location
  copy: src=join-command dest=/tmp/join-command.sh mode=0777

- name: Join the node to cluster
  command: sh /tmp/join-command.sh
