# Step 1: Install Docker and its dependent components.
- name: install Docker
  sudo: yes
  yum:
    name: docker
    state: present
    update_cache: true

- name: start Docker service
  sudo: yes
  service:
    name: docker
    state: started
    enabled: yes
  tags: installation

- name: Ensure group "docker" exists
  sudo: yes
  group:
    name: docker
    state: present

- name: Add centos user to docker group
  user:
    name: centos
    group: docker
  tags: installation

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none
  tags: installation

- name: Disable swap
  command: swapoff -a

- name: Create List of nodes to be added into Cluster
  set_fact: nodelist={%for host in groups['kube-node']%}"{{hostvars[host].ansible_host}}"{% if not loop.last %},{% endif %}{% endfor %}

- debug: msg="{{nodelist}}"

- name: disable SELinux
  command: setenforce 0

- name: disable SELinux on reboot
  selinux:
   state: disabled

#Step 2: Installing k8s prereq (kubelet, kubeadm, kubectl)
- name: add Kubernetes' YUM repository
  yum_repository:
    name: Kubernetes
    description: Kubernetes YUM repository
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: yes

- name: install kubelet
  yum:
    name: kubelet-1.10.12
    #name:  kubelet-1.13.7
    state: present
    update_cache: true

- name: install kubeadm
  yum:
    name: kubeadm-1.10.12
    state: present
- name: install kubectl
  yum:
    name: kubectl-1.10.12
    state: present
    allow_downgrade: yes

- name: start kubelet
  service:
    name: kubelet
    enabled: yes
    state: started

# Step 3: Initialize the Kubernetes cluster with kubeadm using the below code (applicable only on master node).
- name: Initialize Kubernetes cluster using kubeadm
  shell: kubeadm init --apiserver-advertise-address="{{hostvars['final-proj-k8s-master-1'].ansible_host}}" --pod-network-cidr=192.168.0.0/16 --ignore-preflight-errors=all
  become_method: sudo

# Step 4: Setup the k8s config file for the centos user to access the Kubernetes cluster using the below code.

- name: Setup kubeconfig for vagrant user
  command: "{{ item }}"
  with_items:
   - mkdir -p ~/.kube
   - cp -rf /etc/kubernetes/admin.conf ~/.kube/config
   - chown centos:centos  ~/.kube/config

#Step 5: Setup the container networking provider and the network policy engine using the below code.

- name: K8S | Install Master | Install pod network
  shell: kubectl apply -f https://docs.projectcalico.org/v3.7/manifests/calico.yaml

#  shell: kubectl apply -f https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml


# Step 6: Generate kube join command for joining the node to the Kubernetes cluster and store the command in the file named join-command.

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
 # sudo: no
 # become: false
  local_action: copy content="{{ join_command.stdout_lines[0] }} --ignore-preflight-errors=cri" dest="join-command"

# Step 8: Adding --cloud-provider=aws in kube services manifests
- name: Inserting a line (--cloud-provider) after spec > containers > command  
  lineinfile:
    path: /etc/kubernetes/manifests
    line: --cloud-provider=aws
    insertafter: - command: 

# Step 7: Restarting services
- name: reload systemd
  sudo: yes
  command: systemctl daemon-reload

- name: restart kubelet
  become: true
  service: name=kubelet state=restarted

